version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hashchan
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Reth node service
  reth:
    build:
      context: .
      dockerfile: ./reth/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/hashchan
    volumes:
      - reth-data:/app/data
      - ./reth:/usr/src/reth
    ports:
      - "8545:8545"  # JSON-RPC API
      - "8546:8546"  # WebSocket API
      - "30303:30303"  # P2P
      - "30303:30303/udp"  # P2P UDP
    develop:
      watch:
        - action: rebuild
          path: ./reth/src
          target: /usr/src/reth/reth-service/src

  # UI service
  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    depends_on:
      - postgres
      - reth
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/hashchan
      RETH_API_URL: http://reth:8545
    ports:
      - "8000:8000"  # UI interface
    volumes:
      - ./ui:/usr/src/ui
    develop:
      watch:
        - action: rebuild
          path: ./ui/src
          target: /usr/src/ui/ui-service/src

volumes:
  postgres-data:
  reth-data:
